project:
  type: website
  output-dir: docs

website:
  title: "Net Zhang"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/NetZissou
      - icon: twitter
        href: https://twitter.com/NetZissou
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

